BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'customer';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
GO
CREATE TABLE customer(
  idcustomer NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(100) NULL,
  age NUMBER NULL,
  birth DATE NULL,
	surname VARCHAR2(100) NULL,
	stamp DATE NULL,
	random NUMBER NULL,
	curr DECIMAL(19,2) NULL,
  PRIMARY KEY(idcustomer)
)
GO
CREATE OR REPLACE PROCEDURE ctemp
AS
	ind NUMBER := 1;
BEGIN
    WHILE ind < 500
    LOOP
      insert into customer(idcustomer, name, age, birth, surname, stamp, random, curr) values(
        ind,
        CONCAT('name',CAST(ind AS VARCHAR2(6))),
        10+ind,
        TO_DATE('2010-09-24', 'YYYY/MM/DD'),
        CONCAT('surname_', CAST( (ind*2+100000) AS VARCHAR2(80))),
        SYSDATE,
        dbms_random.value()*1000,
        dbms_random.value()*10000
      );
      ind := ind + 1;
    END LOOP;
END;
GO
BEGIN
    ctemp;
END;
GO
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'ctemp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'seller';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
GO
CREATE TABLE seller(
  idseller NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(100) NULL,
  age NUMBER NULL,
  birth DATE NULL,
	surname VARCHAR2(100) NULL,
	stamp DATE NULL,
	random NUMBER NULL,
	curr DECIMAL(19,2) NULL,
  cf VARCHAR2(200),
  PRIMARY KEY(idseller)
)
GO
CREATE OR REPLACE PROCEDURE ctemp
AS
	ind NUMBER := 1;
BEGIN
    WHILE ind < 60
    LOOP
      insert into seller(idseller, name, age, birth, surname, stamp, random, curr, cf) values(
        ind,
        CONCAT('name',CAST(ind AS VARCHAR2(6))),
			  10+ind,
        TO_DATE('2010-09-24', 'YYYY/MM/DD'),
			  CONCAT('surname_', CAST( (ind*2+100000) AS VARCHAR2(80))),
			  SYSDATE,
			  dbms_random.value()*1000,
			  dbms_random.value()*10000,
        CAST( (dbms_random.value()*100000) AS VARCHAR2(6))
      );
      ind := ind + 1;
    END LOOP;
END;
GO
BEGIN
    ctemp;
END;
GO
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'ctemp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'sellerkind';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
GO
CREATE TABLE sellerkind(
  idsellerkind NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(100) NULL,
	rnd NUMBER NULL,
  PRIMARY KEY(idsellerkind)
)
GO

CREATE OR REPLACE PROCEDURE ctemp
AS
	ind NUMBER := 0;
BEGIN
    WHILE ind < 20
    LOOP
        insert into sellerkind(idsellerkind,name,rnd) values(
            ind*30,
            CONCAT('name',CAST((ind*30) AS VARCHAR2(6))),
			dbms_random.value()*1000
        );
        ind := ind + 1;
    END LOOP;
END;
GO
BEGIN
    ctemp;
END;
GO
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'ctemp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'customerkind';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
GO
CREATE TABLE customerkind(
    idcustomerkind NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NULL,
	rnd NUMBER NULL,
    PRIMARY KEY(idcustomerkind)
)
GO
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'ctemp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO
CREATE OR REPLACE PROCEDURE ctemp
AS
	ind NUMBER := 0;
BEGIN
    WHILE ind < 40
    LOOP
        insert into customerkind(idcustomerkind,name,rnd) values(
            ind*3,
            CONCAT('name',CAST((ind*3) AS VARCHAR2(6))),
			dbms_random.value()*1000
        );
        ind := ind + 1;
    END LOOP;
END;
GO
BEGIN
    ctemp;
END;
GO
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'ctemp';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO


BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'testSP2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO
CREATE OR REPLACE PROCEDURE testSP2
(esercizio IN NUMBER, meseinizio IN NUMBER, mess IN VARCHAR2, defparam IN NUMBER DEFAULT 2)
AS
    c1 SYS_REFCURSOR;
BEGIN
    open c1 for
    SELECT 'aa' AS colA, 'bb' AS colB, 12 AS colC, esercizio AS original_esercizio, REPLACE(mess,'a','z') AS newmess, defparam*2 AS newparam
    FROM dual
    CONNECT BY level <= 1;
    
    DBMS_SQL.RETURN_RESULT(c1);
END;
GO


BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'testSP1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO
CREATE OR REPLACE PROCEDURE testSP1
(esercizio IN NUMBER, meseinizio IN NUMBER, mesefine OUT NUMBER, mess IN VARCHAR2, defparam IN NUMBER DEFAULT 2)
AS
    c1 SYS_REFCURSOR;
BEGIN
    mesefine := 12;
    open c1 for
    SELECT 'a' AS colA, 'b' AS colB, 12 AS colC, esercizio AS original_esercizio, REPLACE(mess,'a','z') AS newmess, defparam*2 AS newparam
    FROM dual
    CONNECT BY level <= 1;
    
    DBMS_SQL.RETURN_RESULT(c1);
END;
GO


BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE ' || 'testSP3';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
GO
CREATE OR REPLACE PROCEDURE testSP3
(esercizio IN NUMBER DEFAULT 0)
AS
    c1 SYS_REFCURSOR;
    c2 SYS_REFCURSOR;
    c3 SYS_REFCURSOR;
    c4 SYS_REFCURSOR;
BEGIN
    open c1 for SELECT * FROM customer FETCH NEXT 100 ROWS ONLY;
    open c2 for SELECT * FROM seller FETCH NEXT 100 ROWS ONLY;
    open c3 for SELECT * FROM customerkind FETCH NEXT 10 ROWS ONLY;
    open c4 for SELECT * FROM sellerkind FETCH NEXT 10 ROWS ONLY;
    
    DBMS_SQL.RETURN_RESULT(c1);
    DBMS_SQL.RETURN_RESULT(c2);
    DBMS_SQL.RETURN_RESULT(c3);
    DBMS_SQL.RETURN_RESULT(c4);
END;
GO
